apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - server/secret.yaml
  - server/pvc.yaml
  - server/deployment.yaml
  - server/service.yaml
  - web/configmap.yaml
  - web/deployment.yaml
  - web/service.yaml
  - ingress.yaml
